apiVersion: apps/v1
kind: Deployment
metadata:
  name: solar-system
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: solar-system
  template:
    metadata:
      labels:
        app: solar-system
    spec:
      containers:
      - name: solar-system
        image: 781978598486.dkr.ecr.us-east-1.amazonaws.com/solar-system:latest
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"
        env:
        - name: MONGO_URI
          value: "mongodb+srv://supercluster.d83jj.mongodb.net/superData"
        - name: MONGO_USERNAME
          value: "superuser"
        - name: MONGO_PASSWORD
          value: "SuperPassword"
