- name: Force clean deploy
        run: |
          kubectl delete deployment solar-system --ignore-not-found=true
          sleep 15
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml

      - name: Wait for pod to be Ready
        run: |
          kubectl wait pod \
            -l app=solar-system \
            --for=condition=Ready \
            --timeout=180s

      - name: Set env vars
        run: |
          kubectl set env deployment/solar-system \
            MONGO_URI="mongodb://superuser:SuperPassword@mongodb-svc:27017/solarSystem?authSource=admin" \
            MONGO_USERNAME="superuser" \
            MONGO_PASSWORD="SuperPassword"

      - name: Get app URL
        run: |
          echo "🌍 App URL:"
          kubectl get svc solar-system-svc \
            -o jsonpath='{.status.loadBalancer.ingress[0].hostname}'
